# Generated by Django 3.2.9 on 2021-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
