# Generated by Django 3.2.9 on 2021-11-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating_progress',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
