# Generated by Django 3.2.9 on 2021-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_authquery_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
