# Generated by Django 3.2.9 on 2021-11-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
