# Generated by Django 3.2.9 on 2021-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_fetchdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='msg',
            field=models.IntegerField(default=0),
        ),
    ]
