# Generated by Django 3.2.9 on 2021-12-07 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_profile_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authquery',
            name='handle',
            field=models.CharField(default='mike', max_length=40),
        ),
        migrations.AlterField(
            model_name='authquery',
            name='index',
            field=models.CharField(default='A', max_length=4),
        ),
        migrations.AlterField(
            model_name='authquery',
            name='password',
            field=models.CharField(default='bruh', max_length=128),
        ),
        migrations.AlterField(
            model_name='problem',
            name='index',
            field=models.CharField(default='A', max_length=4),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(default='codeforces', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(default='Mike', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
